version: '2'
services:
    petscommunityapplication-app:
        image: petscommunityapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://petscommunityapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=petsCommunityApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    petscommunityapplication-mongodb:
        extends:
            file: mongodb.yml
            service: petscommunityapplication-mongodb
